//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA39_TEAM5
{
    using System;
    using System.Collections.Generic;
    
    public partial class facilitydetail
    {
        public facilitydetail()
        {
            this.bookingdetails = new HashSet<bookingdetail>();
            this.maintainancedetails = new HashSet<maintainancedetail>();
        }
    
        public string Facility_id { get; set; }
        public string Facility_name { get; set; }
        public string Facility_desc { get; set; }
    
        public virtual ICollection<bookingdetail> bookingdetails { get; set; }
        public virtual ICollection<maintainancedetail> maintainancedetails { get; set; }
    }
}
