//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA39_TEAM5
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintainancedetail
    {
        public string facility_id { get; set; }
        public System.DateTime startdate { get; set; }
        public System.DateTime enddate { get; set; }
    
        public virtual facilitydetail facilitydetail { get; set; }
    }
}
