//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA39_TEAM5
{
    using System;
    using System.Collections.Generic;
    
    public partial class memberdetail
    {
        public memberdetail()
        {
            this.bookingdetails = new HashSet<bookingdetail>();
        }
    
        public string Member_id { get; set; }
        public string Member_name { get; set; }
        public string Gender { get; set; }
        public string Contact_number { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<bookingdetail> bookingdetails { get; set; }
    }
}
